const sgMail = require('@sendgrid/mail')

sgMail.setApiKey(process.env.SENDGRID_API_KEY)

const sendWelcomeEmail = (email, name) => {
    sgMail.send({
        to: email,
        from: 'paturkarr@gmail.com',
        subject: 'Welcome To API Manager!',
        text: `Hello ${name}! \nWelcome to The API Manager Application. It's not only the manager app but more of it. It's huge responsibility is on your shoulder. If your register here, It means that you have a lots of power in your hand and power comes with big responsibility. \n\nWe hope that you will never let us down!`
    })
}

const sendGoodByeEmail = (email, name) => {
    sgMail.send({
        to: email,
        from: 'paturkarr@gmail.com',
        subject: `Good Bye, ${name}!`,
        text: `Bye ${name}! \nThe responsibility given to you, you did it well. Thanks for your service. Hope we will meet soon. \nFor the security reason we are deleting all the api key generated by you!`
    })
}

const sendAPIKey = (keyData, projectData) => {
    sgMail.send({
        to: keyData.email,
        from: 'paturkarr@gmail.com',
        subject: `Your API Key Generated, Enjoy!`,
        text: `Hello ${keyData.name}\nYour API Key is generated for ${projectData.projectName}. We are hoping that you will not going to misuse this key.\n\nAPI Key Details:\nKey Owner: ${keyData.name}\nEmail: ${keyData.email}\nMobile: ${keyData.mobile}\nProject Name: ${projectData.projectName}\nDescription: ${projectData.description}\nBase URL: ${projectData.baseUrl.replace('https://', '')}\nAPI Key: ${keyData.apiKey}\nLimit: ${keyData.limit === 0? '∞': keyData.limit} hits \n\nWARNING: If you misuse this key, your key will be disable and you will be permanently blocked for this service.`
    })
}

const sendOtp = (name, otpData) => {
    sgMail.send({
        to: otpData.email,
        from: 'paturkarr@gmail.com',
        subject: `Hello ${name} | OTP | noreply`,
        text: `Hello ${name}\nYour OTP is ${otpData.otp}. Be quick, it will be expired on ${otpData.expiryDateTime.toLocaleString()}.\nThank You!`
    })
}

module.exports = {
    sendWelcomeEmail,
    sendGoodByeEmail,
    sendAPIKey,
    sendOtp
}